// Server component wrapper for the (client) community detail page, mirroring
// app/event/[id]/layout.tsx.
//
// Its only job is to export `generateMetadata()` so that when a community link
// is pasted into iMessage / WhatsApp / Slack it unfurls with a rich preview (the
// "1b" card). The actual OG *image* is generated by the sibling
// `opengraph-image.tsx` (Next auto-wires it into <meta og:image>).
//
// ⚠️ PARKED 2026-08-14 (MVP) — communities are deferred to Phase 2 and must not
// be visible to users anywhere, including a browser tab or a link unfurl.
//
// The REDIRECT that hides this segment lives in the parent, app/community/
// layout.tsx. What is parked *here* is generateMetadata: metadata resolution is
// a separate pass from rendering, so leaving it live would still print the
// community's name into <title> on the way through the redirect. A static
// `metadata` export replaces it.
//
// PHASE 2 RESTORE: delete the static `metadata` export below and uncomment the
// original generateMetadata block.
import type { Metadata } from "next";

export const metadata: Metadata = { title: "NewFind" };

/* PHASE 2 RESTORE — the real link-unfurl metadata ("1b" card). The OG *image*
   is generated by the sibling opengraph-image.tsx, which Next auto-wires into
   <meta og:image>. Restoring this needs the three imports back:
     import { getCommunityForShare } from "@/lib/community-server";
     import { siteOrigin } from "@/lib/event-server";
     import { locationLabel } from "@/lib/event-media";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const community = await getCommunityForShare(slug);

  if (!community) {
    return { title: "Community · NewFind" };
  }

  const members = community.member_count > 0 ? `${community.member_count} members` : "New community";
  const metaLine = `${community.category} · ${locationLabel(community)} · ${members}`;
  const description = community.description?.trim() || metaLine;
  const url = `${siteOrigin()}/community/${slug}`;

  return {
    metadataBase: new URL(siteOrigin()),
    title: `${community.name} · NewFind`,
    description,
    openGraph: {
      title: community.name,
      description: metaLine,
      siteName: "NewFind",
      type: "website",
      url,
    },
    twitter: {
      card: "summary_large_image",
      title: community.name,
      description: metaLine,
    },
  };
}

*/

export default function CommunityLayout({ children }: { children: React.ReactNode }) {
  return children;
}
