// Server component wrapper for the (client) event detail page.
//
// Its only job is to export `generateMetadata()` so that when an event link is
// pasted into iMessage / WhatsApp / Slack it unfurls with a rich preview (the
// "1b" card). The actual OG *image* is generated by the sibling
// `opengraph-image.tsx` (Next auto-wires it into <meta og:image>).
import type { Metadata } from "next";
import { getEventForShare, siteOrigin } from "@/lib/event-server";
import { locationLabel, priceLabel, shortDate } from "@/lib/event-media";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;
  const event = await getEventForShare(id);

  if (!event) {
    return { title: "Event · NewFind" };
  }

  const place = locationLabel(event);
  const metaLine = `${place} · ${shortDate(event.start_date)} · ${priceLabel(event)}`;
  const description = event.description?.trim() || metaLine;
  const url = `${siteOrigin()}/event/${id}`;

  return {
    metadataBase: new URL(siteOrigin()),
    title: `${event.title} · NewFind`,
    description,
    openGraph: {
      title: event.title,
      description: metaLine,
      siteName: "NewFind",
      type: "website",
      url,
    },
    twitter: {
      card: "summary_large_image",
      title: event.title,
      description: metaLine,
    },
  };
}

export default function EventLayout({ children }: { children: React.ReactNode }) {
  return children;
}
